sudo: false
language: rust
# Required for coverage
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev 

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly


# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

after_success:
  - if [ "$TRAVIS_RUST_VERSION" = "stable" ]; then travis-cargo coveralls --no-sudo --verify; fi