[package]
name = "dwarf_x86"
version = "0.1.0"
authors = ["Ammar Askar <ammar@ammaraskar.com>"]
description = "High level API to read debug info for x86 binaries"
repository = "https://github.com/ammaraskar/rust-dwarf-x86"

[dependencies]
dwarf = "0.0.3"